language: php
php: 5.5
sudo: required
before_script:
- make install
- sudo ldconfig
- make check
script:
- wget https://phar.phpunit.de/phpunit.phar
- chmod +x phpunit.phar
- /usr/bin/php5 phpunit.phar tests/
