language: php
php: 5.5
sudo: required
before_script:
- cat /etc/ld.so.conf
- ls -l /etc/ld.so.conf.d/*.conf
- cat /etc/ld.so.conf.d/*.conf
- echo $LD_LIBRARY_PATH
- sudo apt-get remove libcurl4-gnutls-dev
- make check
- make prepare
- make check
- make install
- make check
