language: php
php: 5.5
sudo: required
before_script:
- make check
- wget https://s3-us-west-2.amazonaws.com/zboota-server/travis-ci+debian+packages/nettle_2.7.1-1_amd64.deb && sudo dpkg -i nettle_2.7.1-1_amd64.deb
- sudo ldconfig -v
- cd /usr/lib/x86_64-linux-gnu/ && sudo rm libgnutls* && cd -
- wget https://s3-us-west-2.amazonaws.com/zboota-server/travis-ci+debian+packages/gnutls_3.1.28-1_amd64.deb && sudo dpkg -i gnutls_3.1.28-1_amd64.deb
- sudo ldconfig -v
- cd /usr/lib/x86_64-linux-gnu/ && sudo rm libcurl* && cd -
- wget https://s3-us-west-2.amazonaws.com/zboota-server/travis-ci+debian+packages/curl_7.42.1-1_amd64.deb && sudo dpkg -i curl_7.42.1-1_amd64.deb
- sudo ldconfig -v
- make check
