language: php
php: 5.5
sudo: required
before_script:
- sudo apt-get remove libcurl4-gnutls-dev
- sudo apt-get install libcurl4-openssl-dev
- make check
- make prepare-dev
- make check
- make installCurl
- make check
